spring.application.name: spring-boot-web-loki-sample
server:
  port: ${port:8080}

#spring:
#  application:
#    name: first-service

#logging:
#  pattern:
#    console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"
#    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
#  level:
#    org.springframework.web: DEBUG
#  file: app.log

springdoc:
  show-actuator: true
  api-docs:
    path: /v3/api-doc
  swagger-ui:
    path: /swagger-ui
application-description: '@project.description@'
application-version: '@project.version@'
management:
  security:
    enabled: false
